In [1]:
import pandas as pd
import numpy as np

# Reproducibility
np.random.seed(42)

# Number of customers
n_customers = 10_000

# Customer IDs
customer_ids = [f"C{10001 + i}" for i in range(n_customers)]

# Indian cities
cities = [
    "Bengaluru",
    "Chennai",
    "Mumbai",
    "Hyderabad",
    "Delhi",
    "Pune",
    "Kolkata",
    "Kochi",
    "Coimbatore",
    "Ahmedabad"
]

# Occupations
occupations = [
    "IT Professional",
    "Business Owner",
    "Government Employee",
    "Private Employee",
    "Teacher",
    "Healthcare Professional",
    "Self Employed",
    "Engineer",
    "Consultant",
    "Other"
]

# Generate customer data
customers = pd.DataFrame({
    "customer_id": customer_ids,
    "age": np.random.randint(21, 66, n_customers),
    "gender": np.random.choice(
        ["Male", "Female"],
        size=n_customers,
        p=[0.55, 0.45]
    ),
    "city": np.random.choice(
        cities,
        size=n_customers
    ),
    "occupation": np.random.choice(
        occupations,
        size=n_customers
    ),
    "annual_income": np.random.randint(
        250000,
        2500001,
        n_customers
    ),
    "customer_since": pd.to_datetime(
        np.random.choice(
            pd.date_range("2010-01-01", "2025-12-31"),
            size=n_customers
        )
    )
})

# Display first 5 customers
customers.head()

,customer_id,age,gender,city,occupation,annual_income,customer_since
0,C10001,59,Male,Delhi,Teacher,418183,2015-02-21
1,C10002,49,Male,Kochi,Teacher,1585307,2010-07-08
2,C10003,35,Female,Kolkata,Other,833642,2013-12-11
3,C10004,63,Male,Coimbatore,Self Employed,1061744,2013-05-05
4,C10005,28,Male,Delhi,Self Employed,357764,2017-02-10

In [2]:
customers.shape

(10000, 7)

In [3]:
print("Shape:", customers.shape)
print("Columns:", customers.columns.tolist())
print("Missing values:")
print(customers.isnull().sum())

Shape: (10000, 7)
Columns: ['customer_id', 'age', 'gender', 'city', 'occupation', 'annual_income', 'customer_since']
Missing values:
customer_id       0
age               0
gender            0
city              0
occupation        0
annual_income     0
customer_since    0
dtype: int64

In [4]:
customers.to_csv("../data/customers.csv", index=False)
print("customers.csv created successfully!")

customers.csv created successfully!

In [5]:
# Generate account data

np.random.seed(42)

# Number of accounts
n_accounts = 13_000

# Account IDs
account_ids = [f"A{10001 + i}" for i in range(n_accounts)]

# Randomly assign customers
account_customer_ids = np.random.choice(
    customers["customer_id"],
    size=n_accounts
)

# Account types
account_types = np.random.choice(
    ["Savings", "Current"],
    size=n_accounts,
    p=[0.75, 0.25]
)

# Account balances
account_balances = np.round(
    np.random.lognormal(
        mean=11,
        sigma=1.0,
        size=n_accounts
    ),
    2
)

# Account opening dates
account_opening_dates = pd.to_datetime(
    np.random.choice(
        pd.date_range("2012-01-01", "2025-12-31"),
        size=n_accounts
    )
)

# Account status
account_status = np.random.choice(
    ["Active", "Inactive"],
    size=n_accounts,
    p=[0.90, 0.10]
)

accounts = pd.DataFrame({
    "account_id": account_ids,
    "customer_id": account_customer_ids,
    "account_type": account_types,
    "balance": account_balances,
    "account_opening_date": account_opening_dates,
    "status": account_status
})

accounts.head()

  account_id customer_id account_type    balance account_opening_date  status
0     A10001      C17271      Current   19781.67           2014-12-20  Active
1     A10002      C10861      Savings  146888.65           2012-09-23  Active
2     A10003      C15391      Savings   45025.59           2015-06-24  Active
3     A10004      C15192      Savings    8114.35           2012-02-04  Active
4     A10005      C15735      Current   25124.52           2025-05-13  Active

In [6]:
print("Shape:", accounts.shape)
print("\nColumns:", accounts.columns.tolist())
print("\nMissing values:")
print(accounts.isnull().sum())

Shape: (13000, 6)

Columns: ['account_id', 'customer_id', 'account_type', 'balance', 'account_opening_date', 'status']

Missing values:
account_id              0
customer_id             0
account_type            0
balance                 0
account_opening_date    0
status                  0
dtype: int64

In [7]:
accounts.to_csv("../data/accounts.csv", index=False)

print("accounts.csv created successfully!")

accounts.csv created successfully!

In [8]:
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

# Load existing accounts
accounts = pd.read_csv("../Data/Accounts.csv")

transactions = []

transaction_types = ["Credit", "Debit", "Transfer"]

for i in range(1, 5001):

    account_id = random.choice(accounts["account_id"].tolist())

    transaction_date = datetime(2025, 1, 1) + timedelta(
        days=random.randint(0, 364)
    )

    transaction_type = random.choice(transaction_types)

    amount = round(random.uniform(100, 50000), 2)

    balance_after_transaction = round(
        random.uniform(1000, 500000), 2
    )

    transactions.append([
        f"T{i:05d}",
        account_id,
        transaction_date.strftime("%Y-%m-%d"),
        transaction_type,
        amount,
        balance_after_transaction
    ])

transactions_df = pd.DataFrame(
    transactions,
    columns=[
        "transaction_id",
        "account_id",
        "transaction_date",
        "transaction_type",
        "amount",
        "balance_after_transaction"
    ]
)

# Save inside Data folder
transactions_df.to_csv("../Data/Transactions.csv", index=False)

print("Transactions.csv created successfully!")
print("Rows:", len(transactions_df))
print(transactions_df.head())

Transactions.csv created successfully!
Rows: 5000
  transaction_id account_id transaction_date transaction_type    amount  \
0         T00001     A20477       2025-02-27           Credit  37103.37
1         T00002     A12287       2025-02-22         Transfer  37059.32
2         T00003     A19675       2025-08-05           Credit   1586.88
3         T00004     A18280       2025-11-05           Credit  28106.13
4         T00005     A21491       2025-10-07            Debit  11099.99

   balance_after_transaction
0                  123201.04
1                  273137.90
2                  110100.35
3                  358293.79
4                  295043.58

In [9]:
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

# Load existing customers
customers = pd.read_csv("../Data/Customers.csv")

loans = []

loan_types = ["Personal", "Home", "Auto", "Education", "Business"]
loan_statuses = ["Active", "Closed", "Default"]

for i in range(1, 2001):

    customer_id = random.choice(customers["customer_id"].tolist())

    loan_type = random.choice(loan_types)

    loan_amount = round(random.uniform(50000, 2500000), 2)

    interest_rate = round(random.uniform(7, 18), 2)

    loan_date = datetime(2024, 1, 1) + timedelta(
        days=random.randint(0, 730)
    )

    loan_status = random.choices(
        loan_statuses,
        weights=[60, 30, 10]
    )[0]

    outstanding_amount = round(
        loan_amount * random.uniform(0, 0.9), 2
    )

    loans.append([
        f"L{i:05d}",
        customer_id,
        loan_type,
        loan_amount,
        interest_rate,
        loan_date.strftime("%Y-%m-%d"),
        loan_status,
        outstanding_amount
    ])

loans_df = pd.DataFrame(
    loans,
    columns=[
        "loan_id",
        "customer_id",
        "loan_type",
        "loan_amount",
        "interest_rate",
        "loan_date",
        "loan_status",
        "outstanding_amount"
    ]
)

# Save inside Data folder
loans_df.to_csv("../Data/Loans.csv", index=False)

print("Loans.csv created successfully!")
print("Rows:", len(loans_df))
print(loans_df.head())

Loans.csv created successfully!
Rows: 2000
  loan_id customer_id loan_type  loan_amount  interest_rate   loan_date  \
0  L00001      C11825  Personal   1866798.72           9.69  2024-05-22
1  L00002      C18936  Personal   1496706.66           7.35  2024-04-05
2  L00003      C10435  Business    537152.24          14.15  2025-07-12
3  L00004      C14558  Personal   1909078.05           8.76  2025-03-08
4  L00005      C15515  Personal    277227.32           8.06  2024-12-18

  loan_status  outstanding_amount
0      Closed          1136935.56
1      Active           680731.76
2      Active           217164.28
3      Active           267140.25
4      Closed           201382.21